apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: customer
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: docker.io/fabricio211/customer-service
spec:
  destination:
    namespace: customer
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm
    repoURL: https://github.com/fabriciolfj/customer-service-k8s
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated: {}